# Generated by Django 3.2.9 on 2021-11-20 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
