# Generated by Django 3.2.9 on 2021-11-23 12:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='articles_images/%Y/%m/%d/'),
        ),
    ]
