# Generated by Django 3.2.9 on 2021-11-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
